// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// marshall_find_stable_matching
Rcpp::List marshall_find_stable_matching(Rcpp::DataFrame df_pref1, Rcpp::DataFrame df_pref2);
RcppExport SEXP _stablemarriageR_marshall_find_stable_matching(SEXP df_pref1SEXP, SEXP df_pref2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type df_pref1(df_pref1SEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type df_pref2(df_pref2SEXP);
    rcpp_result_gen = Rcpp::wrap(marshall_find_stable_matching(df_pref1, df_pref2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_stablemarriageR_marshall_find_stable_matching", (DL_FUNC) &_stablemarriageR_marshall_find_stable_matching, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_stablemarriageR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
