# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

marshall_find_stable_matching <- function(df_pref1, df_pref2) {
    .Call(`_stablemarriageR_marshall_find_stable_matching`, df_pref1, df_pref2)
}

